### ISSUE TITLE
[資料串接] Data 來源改成吃DB的

### ISSUE THREAD

**Issue by peihsuan** [winonecheng/Lab_mosquito#1]

**Comment by winonecheng** [comment]
疫情地圖中，腸病毒頁面顯示的資料為，DB內user table的data，
先確認可以從DB拿資料顯示在地圖上。

登革熱和流感的資料，仍是static file，沒有放到DB上
因為不確定之後拿到的疫情 data，是不是要丟到DB上，或是read file即可

**Comment by peihsuan** [comment]
那先用Readfile 好了~~ 
等後端DB 需求更明確之後 我們再改成DB :D
