### ISSUE TITLE
[資料] 條列診所需上傳什麼資料

### ISSUE THREAD

**Issue by peihsuan** [winonecheng/Lab_mosquito#4]
診所需上傳什麼資料

**Comment by peihsuan** [comment]
第一版 : 預設用 bot 回報 

-- 
診所: 發燒: 2 咳嗽: 3 
Bot : XX診所，謝謝! 已收到您的回報資訊! 

--
預設欄位: 發燒、咳嗽、登革熱

**Comment by winonecheng** [comment]
那我這回報的資料傳上DB時，使用的地址就是診所的位置嗎?

**Comment by winonecheng** [comment]
我預想的流程是：
診所要回報 -> bot回傳confirm先確認地址 -> 正確，開始用文字回報 -> 回傳confirm 確認回報資料正確
　　　　　　　　　　　　　　　　　　　-> 錯誤，引導至設定地址

**Comment by peihsuan** [comment]
嗯嗯，我想的流程目前也是這樣 :)

**Comment by winonecheng** [comment]
流程部分已經完成，只差把回報的資料傳上DB

**Comment by winonecheng** [comment]
此版本暫時不須傳上DB
