### ISSUE TITLE
[Bot] User 要可以改地址

### ISSUE THREAD

**Issue by peihsuan** [winonecheng/Lab_mosquito#6]

**Comment by winonecheng** [comment]
完成
輸入 1 可以設定地址
且可選擇 要使用何種方式設定


<img src="https://cloud.githubusercontent.com/assets/11289632/25009325/da40e6e8-2098-11e7-81c6-d0e21e8b7955.jpg" width="300">

**Comment by peihsuan** [comment]
@winonecheng 另外想問一下，User手動輸入地址的話，目前有串google API 轉經緯度了媽?  :D

**Comment by winonecheng** [comment]
有 可以了~
